FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*", ImGui = "*", ImGuiImplOpenGL3 = "*", glfw-beef = "*", ImGuiImplGlfw = "*"}

[Project]
Name = "Boids"
StartupObject = "Boids.Program"
ProcessorMacros = ["UseKDTree"]

[Configs.Debug.Win64]
OptimizationLevel = "OgPlus"

[Configs.Release.Win64]
CLibType = "Dynamic"
