FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*"}

[Project]
Name = "Boids"
StartupObject = "Boids.Program"
ProcessorMacros = ["UseKDTree"]

[Configs.Debug.Win64]
OptimizationLevel = "OgPlus"

[Configs.Release.Win64]
CLibType = "Dynamic"
VectorizeLoops = true
